name: onsets_frames_semisup

channels:
  - pytorch
  - defaults
  - conda-forge
  - nvidia

dependencies:
  - python ==3.11.9
  - pip ==23.3.1
  - numpy ==1.26.4
  - scipy ==1.13.1
  - pandas ==1.5.3
  - scikit-learn ==1.4.2
  - tqdm ==4.66.4
  - pytorch::pytorch ==2.3.1
  - pytorch::torchvision ==0.18.1
  - pytorch::torchaudio ==2.3.1
  - pytorch::pytorch-cuda ==11.8
  - cudatoolkit ==11.8.0
  - pip:
    - torchinfo ==1.8.0
    - tensorboard ==2.17.0
    - SoundFile ==0.12.1
    - sacred ==0.8.5
    - librosa ==0.10.2
    - mir-eval ==0.7
    - mido ==1.3.2
    - Pillow ==10.4.0
